// Full 100 product definitions with proper names
export const ALL_PRODUCTS_META = [
  // RAU CỦ (p001-p018)
  { id: "p001", name: "Cà chua", nameEn: "Fresh Tomatoes", category: "rau-cu", unit: "kg", price: 25000 },
  { id: "p002", name: "Cà rốt Đà Lạt", nameEn: "Dalat Carrots", category: "rau-cu", unit: "kg", price: 22000 },
  { id: "p003", name: "Khoai tây vàng", nameEn: "Yellow Potatoes", category: "rau-cu", unit: "kg", price: 28000 },
  { id: "p004", name: "Bí đỏ", nameEn: "Pumpkin", category: "rau-cu", unit: "kg", price: 20000 },
  { id: "p005", name: "Hành tây", nameEn: "Yellow Onions", category: "rau-cu", unit: "kg", price: 18000 },
  { id: "p006", name: "Rau muống", nameEn: "Water Spinach", category: "rau-cu", unit: "kg", price: 15000 },
  { id: "p007", name: "Bắp cải trắng", nameEn: "White Cabbage", category: "rau-cu", unit: "kg", price: 18000 },
  { id: "p008", name: "Súp lơ xanh", nameEn: "Broccoli", category: "rau-cu", unit: "kg", price: 35000 },
  { id: "p009", name: "Ớt chuông đỏ", nameEn: "Red Bell Pepper", category: "rau-cu", unit: "kg", price: 45000 },
  { id: "p010", name: "Tỏi Bắc", nameEn: "Northern Garlic", category: "rau-cu", unit: "kg", price: 55000 },
  { id: "p011", name: "Chanh không hạt", nameEn: "Seedless Limes", category: "rau-cu", unit: "kg", price: 20000 },
  { id: "p012", name: "Xà lách lolo", nameEn: "Lollo Rosso Lettuce", category: "rau-cu", unit: "kg", price: 30000 },
  { id: "p049", name: "Cải thảo", nameEn: "Napa Cabbage", category: "rau-cu", unit: "kg", price: 22000 },
  { id: "p050", name: "Đậu bắp", nameEn: "Okra", category: "rau-cu", unit: "kg", price: 25000 },
  { id: "p051", name: "Ngô ngọt", nameEn: "Sweet Corn", category: "rau-cu", unit: "trái", price: 8000 },
  { id: "p052", name: "Khoai lang tím", nameEn: "Purple Sweet Potato", category: "rau-cu", unit: "kg", price: 32000 },
  { id: "p053", name: "Rau cần tây", nameEn: "Celery", category: "rau-cu", unit: "bó", price: 18000 },
  { id: "p054", name: "Mướp hương", nameEn: "Luffa (Sponge Gourd)", category: "rau-cu", unit: "kg", price: 15000 },

  // THỊT (p013-p020)
  { id: "p013", name: "Nạc dăm heo", nameEn: "Pork Collar (Nạc Dăm)", category: "thit", unit: "kg", price: 140000 },
  { id: "p014", name: "Ba rọi heo rút sườn", nameEn: "Pork Belly Boneless", category: "thit", unit: "kg", price: 165000 },
  { id: "p015", name: "Sườn non heo", nameEn: "Pork Spare Ribs", category: "thit", unit: "kg", price: 175000 },
  { id: "p016", name: "Thịt bò Úc (Thăn)", nameEn: "Australian Beef Sirloin", category: "thit", unit: "kg", price: 250000 },
  { id: "p017", name: "Bắp bò", nameEn: "Beef Shank", category: "thit", unit: "kg", price: 220000 },
  { id: "p018", name: "Xương ống heo", nameEn: "Pork Marrow Bones", category: "thit", unit: "kg", price: 80000 },
  { id: "p019", name: "Thịt heo xay", nameEn: "Ground Pork", category: "thit", unit: "kg", price: 120000 },
  { id: "p020", name: "Thăn bò ngoại", nameEn: "Beef Striploin", category: "thit", unit: "kg", price: 280000 },
  { id: "p055", name: "Thịt bò xay", nameEn: "Ground Beef", category: "thit", unit: "kg", price: 180000 },
  { id: "p056", name: "Cốt lết heo", nameEn: "Pork Chops", category: "thit", unit: "kg", price: 155000 },
  { id: "p057", name: "Nạc vai heo", nameEn: "Pork Shoulder", category: "thit", unit: "kg", price: 135000 },
  { id: "p058", name: "Gan heo", nameEn: "Pork Liver", category: "thit", unit: "kg", price: 70000 },
  { id: "p059", name: "Gân bò", nameEn: "Beef Tendon", category: "thit", unit: "kg", price: 160000 },
  { id: "p060", name: "Thịt dê (Đùi)", nameEn: "Goat Leg Meat", category: "thit", unit: "kg", price: 200000 },

  // HẢI SẢN (p021-p028)
  { id: "p021", name: "Cá hồi tươi (Fillet)", nameEn: "Fresh Salmon Fillet", category: "hai-san", unit: "kg", price: 320000 },
  { id: "p022", name: "Tôm sú size lớn", nameEn: "Large Black Tiger Shrimp", category: "hai-san", unit: "kg", price: 280000 },
  { id: "p023", name: "Mực ống", nameEn: "Squid Tubes", category: "hai-san", unit: "kg", price: 250000 },
  { id: "p024", name: "Bạch tuộc", nameEn: "Octopus", category: "hai-san", unit: "kg", price: 180000 },
  { id: "p025", name: "Cá basa (Fillet)", nameEn: "Basa Catfish Fillet", category: "hai-san", unit: "kg", price: 65000 },
  { id: "p026", name: "Cá thu cắt lát", nameEn: "Sliced King Mackerel", category: "hai-san", unit: "kg", price: 220000 },
  { id: "p027", name: "Ngao hai cùi", nameEn: "Fresh Clams", category: "hai-san", unit: "kg", price: 120000 },
  { id: "p028", name: "Cua biển thịt", nameEn: "Sea Crab (Meat Full)", category: "hai-san", unit: "kg", price: 450000 },
  { id: "p061", name: "Tôm thẻ chân trắng", nameEn: "White Leg Shrimp", category: "hai-san", unit: "kg", price: 180000 },
  { id: "p062", name: "Cá chẽm", nameEn: "Sea Bass (Barramundi)", category: "hai-san", unit: "kg", price: 160000 },
  { id: "p063", name: "Tôm hùm Baby", nameEn: "Baby Lobster", category: "hai-san", unit: "con", price: 350000 },
  { id: "p064", name: "Hàu biển", nameEn: "Fresh Oysters", category: "hai-san", unit: "kg", price: 200000 },
  { id: "p065", name: "Cá ngừ (Loin)", nameEn: "Tuna Loin", category: "hai-san", unit: "kg", price: 280000 },
  { id: "p066", name: "Ghẹ xanh", nameEn: "Blue Swimmer Crab", category: "hai-san", unit: "kg", price: 320000 },

  // GÀ VỊT (p029-p034)
  { id: "p029", name: "Gà ta nguyên con", nameEn: "Whole Free-range Chicken", category: "ga-vit", unit: "con", price: 150000 },
  { id: "p030", name: "Đùi gà", nameEn: "Chicken Drumsticks", category: "ga-vit", unit: "kg", price: 65000 },
  { id: "p031", name: "Cánh gà", nameEn: "Chicken Wings", category: "ga-vit", unit: "kg", price: 85000 },
  { id: "p032", name: "Trứng gà ta", nameEn: "Free-range Chicken Eggs", category: "ga-vit", unit: "vỉ 10", price: 90000 },
  { id: "p033", name: "Trứng cút", nameEn: "Quail Eggs", category: "ga-vit", unit: "vỉ 30", price: 45000 },
  { id: "p034", name: "Ức gà phi lê", nameEn: "Chicken Breast Fillet", category: "ga-vit", unit: "kg", price: 75000 },
  { id: "p067", name: "Vịt nguyên con", nameEn: "Whole Duck", category: "ga-vit", unit: "con", price: 170000 },
  { id: "p068", name: "Gà công nghiệp", nameEn: "Broiler Chicken", category: "ga-vit", unit: "con", price: 100000 },
  { id: "p069", name: "Chân gà", nameEn: "Chicken Feet", category: "ga-vit", unit: "kg", price: 55000 },
  { id: "p070", name: "Trứng vịt muối", nameEn: "Salted Duck Eggs", category: "ga-vit", unit: "trứng", price: 12000 },
  { id: "p071", name: "Lòng gà", nameEn: "Chicken Giblets", category: "ga-vit", unit: "kg", price: 50000 },
  { id: "p072", name: "Xương gà hầm", nameEn: "Chicken Carcass (for broth)", category: "ga-vit", unit: "kg", price: 40000 },

  // ĐÔNG LẠNH (p035-p041)
  { id: "p035", name: "Xúc xích Đức Việt", nameEn: "Duc Viet German Sausage", category: "dong-lanh", unit: "gói", price: 55000 },
  { id: "p036", name: "Chả giò rế", nameEn: "Crispy Net Spring Rolls", category: "dong-lanh", unit: "gói", price: 85000 },
  { id: "p037", name: "Cá viên chiên", nameEn: "Fried Fish Cake Balls", category: "dong-lanh", unit: "gói", price: 70000 },
  { id: "p038", name: "Khoai tây chiên đông lạnh", nameEn: "Frozen French Fries", category: "dong-lanh", unit: "gói", price: 110000 },
  { id: "p039", name: "Há cảo tôm thịt", nameEn: "Shrimp & Pork Dim Sum", category: "dong-lanh", unit: "gói", price: 120000 },
  { id: "p040", name: "Phô mai que", nameEn: "Mozzarella Cheese Sticks", category: "dong-lanh", unit: "gói", price: 95000 },
  { id: "p041", name: "Bò viên", nameEn: "Beef Meatballs", category: "dong-lanh", unit: "gói", price: 85000 },
  { id: "p073", name: "Tôm chiên xù đông lạnh", nameEn: "Frozen Breaded Shrimp", category: "dong-lanh", unit: "gói", price: 130000 },
  { id: "p074", name: "Chả lụa đông lạnh", nameEn: "Frozen Vietnamese Ham (Chả Lụa)", category: "dong-lanh", unit: "cái", price: 75000 },
  { id: "p075", name: "Cá hồi phi lê đông lạnh", nameEn: "Frozen Salmon Fillet", category: "dong-lanh", unit: "gói", price: 250000 },
  { id: "p076", name: "Gà viên đông lạnh", nameEn: "Frozen Chicken Nuggets", category: "dong-lanh", unit: "gói", price: 90000 },
  { id: "p077", name: "Sủi cảo đông lạnh", nameEn: "Frozen Wontons", category: "dong-lanh", unit: "gói", price: 75000 },
  { id: "p078", name: "Pizza đông lạnh", nameEn: "Frozen Mini Pizza", category: "dong-lanh", unit: "cái", price: 120000 },

  // GIA VỊ (p042-p048)
  { id: "p042", name: "Nước mắm Nam Ngư", nameEn: "Nam Ngu Fish Sauce", category: "gia-vi", unit: "chai 500ml", price: 45000 },
  { id: "p043", name: "Dầu ăn Tường An 5L", nameEn: "Tuong An Cooking Oil 5L", category: "gia-vi", unit: "can", price: 250000 },
  { id: "p044", name: "Tương ớt Chinsu", nameEn: "Chinsu Chili Sauce", category: "gia-vi", unit: "chai", price: 25000 },
  { id: "p045", name: "Đường tinh luyện Biên Hòa", nameEn: "Bien Hoa Refined Sugar", category: "gia-vi", unit: "kg", price: 22000 },
  { id: "p046", name: "Bột ngọt Ajinomoto", nameEn: "Ajinomoto MSG 454g", category: "gia-vi", unit: "gói", price: 65000 },
  { id: "p047", name: "Tiêu sọ Phú Quốc", nameEn: "Phu Quoc White Peppercorns", category: "gia-vi", unit: "hũ", price: 85000 },
  { id: "p048", name: "Muối i-ốt Masan", nameEn: "Masan Iodized Salt", category: "gia-vi", unit: "gói", price: 8000 },
  { id: "p079", name: "Nước tương Maggi", nameEn: "Maggi Soy Sauce", category: "gia-vi", unit: "chai", price: 30000 },
  { id: "p080", name: "Hạt nêm Knorr gà", nameEn: "Knorr Chicken Seasoning Powder", category: "gia-vi", unit: "gói", price: 55000 },
  { id: "p081", name: "Dấm gạo Việt Nam", nameEn: "Vietnamese Rice Vinegar", category: "gia-vi", unit: "chai", price: 18000 },
  { id: "p082", name: "Bơ Anchor", nameEn: "Anchor Butter", category: "gia-vi", unit: "hộp 200g", price: 85000 },
  { id: "p083", name: "Mật ong nguyên chất", nameEn: "Pure Honey", category: "gia-vi", unit: "hũ 500g", price: 150000 },
  { id: "p084", name: "Nước cốt dừa Chaokoh", nameEn: "Chaokoh Coconut Cream", category: "gia-vi", unit: "hộp", price: 35000 },
  { id: "p085", name: "Sốt cà chua Heinz", nameEn: "Heinz Tomato Ketchup", category: "gia-vi", unit: "chai", price: 55000 },
  { id: "p086", name: "Bột mì đa dụng", nameEn: "All-purpose Flour", category: "gia-vi", unit: "kg", price: 30000 },
  { id: "p087", name: "Bột bắp (Maizena)", nameEn: "Cornstarch (Maizena)", category: "gia-vi", unit: "gói 400g", price: 25000 },
  { id: "p088", name: "Ớt khô", nameEn: "Dried Red Chili", category: "gia-vi", unit: "gói", price: 35000 },
  { id: "p089", name: "Quế thanh", nameEn: "Cinnamon Sticks", category: "gia-vi", unit: "gói", price: 40000 },
  { id: "p090", name: "Hồi hoa", nameEn: "Star Anise", category: "gia-vi", unit: "gói", price: 45000 },
  { id: "p091", name: "Sả khô", nameEn: "Dried Lemongrass", category: "gia-vi", unit: "gói", price: 20000 },
  { id: "p092", name: "Gừng khô xay", nameEn: "Ground Ginger", category: "gia-vi", unit: "hũ", price: 30000 },
  { id: "p093", name: "Nghệ bột", nameEn: "Turmeric Powder", category: "gia-vi", unit: "hũ", price: 28000 },
  { id: "p094", name: "Nước mắm Phú Quốc", nameEn: "Phu Quoc Premium Fish Sauce", category: "gia-vi", unit: "chai 500ml", price: 80000 },
  { id: "p095", name: "Tương đen Kecap Manis", nameEn: "Sweet Dark Soy Sauce", category: "gia-vi", unit: "chai", price: 42000 },
  { id: "p096", name: "Súp miso Nhật", nameEn: "Japanese Miso Paste", category: "gia-vi", unit: "hộp", price: 95000 },
  { id: "p097", name: "Dầu mè rang", nameEn: "Toasted Sesame Oil", category: "gia-vi", unit: "chai", price: 65000 },
  { id: "p098", name: "Bột cà ri vàng", nameEn: "Yellow Curry Powder", category: "gia-vi", unit: "hũ", price: 38000 },
  { id: "p099", name: "Bột ớt Hàn Quốc (Gochugaru)", nameEn: "Korean Red Pepper Flakes (Gochugaru)", category: "gia-vi", unit: "gói", price: 75000 },
  { id: "p100", name: "Xốt oyster Lee Kum Kee", nameEn: "Lee Kum Kee Oyster Sauce", category: "gia-vi", unit: "chai", price: 55000 },
];
